### ISSUE TITLE
Remove GitHub sign-in extra code from [...nextauth].ts

### ISSUE THREAD

**Issue by nkalupahana** [VandyHacks/witness#127]
This code has been added to NextAuth, and thus is no longer needed here.

**Comment by aadibajpai** [comment]
has been done already https://github.com/VandyHacks/witness/commit/075678f409814c607c4bdb093fe2b7a92fe106b4#diff-81bbae584d6e4013646bc9157027ef5f1be981ea6f3ea39869c7c4a4cbdb3997
