### ISSUE TITLE
[BUG REPORT] Bug found by Hacker on 10/28/2023 at
					 2:16 PM CT

### ISSUE THREAD

**Issue by jacoblurie29** [VandyHacks/witness#439]
# Bug Report 
This is a bug report. You can track this issue in the organizer dashboard.
### Reporter Information 
Role: Hacker
Issue was reported on 10/28/2023 at  2:16 PM CT	
### Description 
The URL "https://apply.vandyhacks.org/api/leaderboard" exposes the user email, and team object (which exposes the team invite code).
It's possible to join any team on the leaderboard, then change their name/devpost link.

**Comment by zineanteoh** [comment]
Fixed with commit https://github.com/VandyHacks/witness/commit/c0750e481187f8254790f563102068903332f056
